name: Deploy
on:
  push:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: LOCAL
    steps:
      - name: Create Database .env file
        run: echo "TODO deployment"
