name: Pull Request Check
on:
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: LOCAL
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.8.0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Create Dabase .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > ./packages/db/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ./packages/db/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./packages/db/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> ./packages/db/.env

      - name: Run Database
        run: |
          pnpm exec turbo db:start
          pnpm exec turbo db:migrate

      # - name: Run Unit Tests
      #   run: pnpm exec turbo test

      - name: Run E2E Tests
        run: pnpm exec turbo e2e:run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
